CREATE TABLE PRODUIT (ID INTEGER AUTO_INCREMENT NOT NULL, LIBELLE VARCHAR(50), PRIX DOUBLE, QUANTITE INTEGER, IDCAT_ID INTEGER, PRIMARY KEY (ID))
CREATE TABLE CATEGORIE (ID INTEGER AUTO_INCREMENT NOT NULL, LIBELLE VARCHAR(50), PRIMARY KEY (ID))
ALTER TABLE PRODUIT ADD CONSTRAINT FK_PRODUIT_IDCAT_ID FOREIGN KEY (IDCAT_ID) REFERENCES CATEGORIE (ID)
